### ISSUE TITLE
New Courses have been Added

### ISSUE THREAD

**Issue by omsv135** [akshayrathigithub/CPI-SPI-Calculator#1]
At present, the website lists CHM, AE, BSBE, CHE, CE, CSE, ES, ECO, EE, MSE, MTH, ME, PHY. Although in 2021-22 academic year, the branch SDS has been added which also has some new courses which have not been given any code as of now.

**Comment by akshayrathigithub** [comment]
#Fix: https://github.com/akshayrathigithub/CPI-SPI-Calculator/pull/6

**Comment by akshayrathigithub** [comment]
Fix: https://github.com/akshayrathigithub/CPI-SPI-Calculator/pull/6
